# Generated by Django 2.2.1 on 2019-05-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionType',
        ),
    ]
