# Generated by Django 2.2.1 on 2019-05-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0002_remove_question_questiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HrSurvey.Question'),
        ),
    ]
