# Generated by Django 2.2.1 on 2019-05-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0004_auto_20190529_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
