# Generated by Django 2.2.1 on 2019-06-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0006_auto_20190603_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='HrSurvey.Survey')),
            ],
        ),
    ]
