# Generated by Django 2.2.1 on 2019-06-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0007_activesurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ActiveSurvey',
        ),
    ]
