# Generated by Django 2.2.1 on 2019-06-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0009_responses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='option_id',
        ),
    ]
