# Generated by Django 2.2.1 on 2019-06-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0010_auto_20190607_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responses',
        ),
    ]
