# Generated by Django 2.2.1 on 2019-06-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0011_delete_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('option', models.TextField()),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_id', to='HrSurvey.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='HrSurvey.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_id', to='HrSurvey.Survey')),
            ],
        ),
    ]
