# Generated by Django 2.2.1 on 2019-06-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0014_auto_20190610_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='responses',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='HrSurvey.Employee'),
            preserve_default=False,
        ),
    ]
