# Generated by Django 2.2.1 on 2019-06-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0017_auto_20190610_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='employee',
        ),
    ]
