# Generated by Django 2.2.1 on 2019-06-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0018_remove_responses_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='HrSurvey.Employee'),
            preserve_default=False,
        ),
    ]
