# Generated by Django 2.2.1 on 2019-06-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0019_responses_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to='HrSurvey.Survey')),
            ],
        ),
        migrations.RemoveField(
            model_name='responses',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='responses',
            name='survey_response',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to='HrSurvey.SurveyResponse'),
            preserve_default=False,
        ),
    ]
