# Generated by Django 2.2.1 on 2019-06-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HrSurvey', '0020_auto_20190610_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='survey_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to='HrSurvey.SurveyResponse'),
        ),
    ]
